{% set version = "1.1.3" %}

package:
  name: infomap
  version: {{ version }}

source:
  url: https://github.com/mapequation/infomap/archive/v{{ version }}.tar.gz
  sha256: e0c2a076ee9e6d87e2969f1a85aef2772141027781707dbb01d16c51fc5a4d9a

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - libgomp  # [linux]

test:
  commands:
    - Infomap -h

about:
  home: https://github.com/mapequation/infomap
  license: AGPL-3.0
  license_family: GPL
  license_file: LICENSE_AGPLv3.txt
  summary: Multi-level network clustering based on the Map Equation
  description: |
    Multi-level network clustering based on the Map Equation.
  doc_url: https://github.com/mapequation/infomap/tree/master/docs
  dev_url: https://github.com/mapequation/infomap

extra:
  recipe-maintainers:
    - vinisalazar
