{% set version = "1.3.0" %}

package:
  name: infomap
  version: {{ version }}

source:
  url: https://github.com/mapequation/infomap/archive/v{{ version }}.tar.gz
  sha256: aa6e5daee83fea3c866641d8a046a2f4ee761024a864c6911020f9ef2c85ecd0

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - libgomp  # [linux]

test:
  commands:
    - Infomap -h

about:
  home: https://github.com/mapequation/infomap
  license: AGPL-3.0
  license_family: GPL
  license_file: LICENSE_AGPLv3.txt
  summary: Multi-level network clustering based on the Map Equation
  description: |
    Multi-level network clustering based on the Map Equation.
  doc_url: https://github.com/mapequation/infomap/tree/master/docs
  dev_url: https://github.com/mapequation/infomap

extra:
  recipe-maintainers:
    - vinisalazar
