{% set name = "infomap" %}
{% set version = "2.8.2" %}

package:
  name: infomap
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/infomap-{{ version }}.tar.gz
  sha256: 0f0ccabe933319ce76447152818b063c44e486584ad6d8bd81555e8e74057cce

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - libgomp  # [linux]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - infomap
    - package_meta
  commands:
    - pip check
    - infomap --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://mapequation.github.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Multi-level network clustering based on the Map Equation
  description: |
    Multi-level network clustering based on the Map Equation.
  doc_url: https://mapequation.github.io/infomap/python/
  dev_url: https://github.com/mapequation/infomap

extra:
  recipe-maintainers:
    - apcamargo
    - vinisalazar
