{% set version = "1.2.0" %}

package:
  name: infomap
  version: {{ version }}

source:
  url: https://github.com/mapequation/infomap/archive/v{{ version }}.tar.gz
  sha256: 85ac3498966d9a13c063dfa2db812ccab0a75d3eda7e7532d4d3718e85e69d89

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - libgomp  # [linux]

test:
  commands:
    - Infomap -h

about:
  home: https://github.com/mapequation/infomap
  license: AGPL-3.0
  license_family: GPL
  license_file: LICENSE_AGPLv3.txt
  summary: Multi-level network clustering based on the Map Equation
  description: |
    Multi-level network clustering based on the Map Equation.
  doc_url: https://github.com/mapequation/infomap/tree/master/docs
  dev_url: https://github.com/mapequation/infomap

extra:
  recipe-maintainers:
    - vinisalazar
