{% set version = "1.5.0" %}

package:
  name: infomap
  version: {{ version }}

source:
  url: https://github.com/mapequation/infomap/archive/v{{ version }}.tar.gz
  sha256: 2b497d2497627cf7eda389f092fbcb007924a4ee468b0632f793a2c731112358

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - libgomp  # [linux]

test:
  commands:
    - Infomap -h

about:
  home: https://github.com/mapequation/infomap
  license: AGPL-3.0
  license_family: GPL
  license_file: LICENSE_AGPLv3.txt
  summary: Multi-level network clustering based on the Map Equation
  description: |
    Multi-level network clustering based on the Map Equation.
  doc_url: https://github.com/mapequation/infomap/tree/master/docs
  dev_url: https://github.com/mapequation/infomap

extra:
  recipe-maintainers:
    - vinisalazar
