{% set version = "2.8.0" %}

package:
  name: infomap
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/infomap-{{ version }}.tar.gz
  sha256: 17eff0882afa5de9bf68f2fba013b06be43d618191859e6723e008e744944e36

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - libgomp  # [linux]
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - infomap
    - package_meta
  commands:
    - pip check
    - infomap --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://mapequation.github.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE_AGPLv3.txt
  summary: Multi-level network clustering based on the Map Equation
  description: |
    Multi-level network clustering based on the Map Equation.
  doc_url: https://mapequation.github.io/infomap/python/
  dev_url: https://github.com/mapequation/infomap

extra:
  recipe-maintainers:
    - apcamargo
    - vinisalazar
